const itemsToAdd = [
  {
    name: 'Apple',
    category: 'Fruit',
    description: 'Fresh and crisp apple',
    price: 0.75,
    quantity: 50,
    stock: 50,
    maxStock: 100,
    minStock: 10,
    expirationDate: '2023-12-31', // Format: YYYY-MM-DD
    unit: 'kg',
    purchasePrice: 0.5,
  },
  {
    name: 'Banana',
    category: 'Fruit',
    description: 'Ripe and sweet banana',
    price: 0.5,
    quantity: 60,
    stock: 60,
    maxStock: 120,
    minStock: 20,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.3,
  },
  // Add more items with the same format
  {
    name: 'Carrot',
    category: 'Vegetable',
    description: 'Organic carrot',
    price: 0.4,
    quantity: 30,
    stock: 30,
    maxStock: 60,
    minStock: 15,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.3,
  },
  {
    name: 'Milk',
    category: 'Dairy',
    description: 'Whole milk',
    price: 2.0,
    quantity: 20,
    stock: 20,
    maxStock: 40,
    minStock: 10,
    expirationDate: '2023-12-31',
    unit: 'l',
    purchasePrice: 1.5,
  },
  {
    name: 'Eggs',
    category: 'Dairy',
    description: 'Fresh farm eggs',
    price: 1.5,
    quantity: 40,
    stock: 40,
    maxStock: 80,
    minStock: 20,
    expirationDate: '2023-12-31',
    unit: 'dozen',
    purchasePrice: 1.0,
  },
  {
    name: 'Orange',
    category: 'Fruit',
    description: 'Juicy and tangy orange',
    price: 1.0,
    quantity: 40,
    stock: 40,
    maxStock: 80,
    minStock: 20,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.7,
  },
  {
    name: 'Spinach',
    category: 'Vegetable',
    description: 'Fresh spinach leaves',
    price: 0.6,
    quantity: 25,
    stock: 25,
    maxStock: 50,
    minStock: 10,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.4,
  },
  {
    name: 'Cheese',
    category: 'Dairy',
    description: 'Cheddar cheese block',
    price: 3.5,
    quantity: 15,
    stock: 15,
    maxStock: 30,
    minStock: 5,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 2.8,
  },
  {
    name: 'Tomato',
    category: 'Vegetable',
    description: 'Ripe red tomato',
    price: 0.8,
    quantity: 35,
    stock: 35,
    maxStock: 70,
    minStock: 15,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.6,
  },
  {
    name: 'Bread',
    category: 'Other',
    description: 'Whole wheat bread loaf',
    price: 2.0,
    quantity: 30,
    stock: 30,
    maxStock: 60,
    minStock: 20,
    expirationDate: '2023-12-31',
    unit: 'piece',
    purchasePrice: 1.5,
  },
  {
    name: 'Chicken Breast',
    category: 'Meat',
    description: 'Boneless chicken breast',
    price: 5.0,
    quantity: 20,
    stock: 20,
    maxStock: 40,
    minStock: 10,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 4.0,
  },
  {
    name: 'Salmon',
    category: 'Seafood',
    description: 'Fresh salmon fillet',
    price: 8.0,
    quantity: 10,
    stock: 10,
    maxStock: 20,
    minStock: 5,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 7.0,
  },
  {
    name: 'Potato',
    category: 'Vegetable',
    description: 'Russet potato',
    price: 0.5,
    quantity: 50,
    stock: 50,
    maxStock: 100,
    minStock: 25,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.3,
  },
  {
    name: 'Pasta',
    category: 'Other',
    description: 'Spaghetti pasta',
    price: 1.2,
    quantity: 40,
    stock: 40,
    maxStock: 80,
    minStock: 20,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.9,
  },
  {
    name: 'Yogurt',
    category: 'Dairy',
    description: 'Greek yogurt',
    price: 2.5,
    quantity: 30,
    stock: 30,
    maxStock: 60,
    minStock: 15,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 1.8,
  },
  {
    name: 'Cucumber',
    category: 'Vegetable',
    description: 'Fresh cucumber',
    price: 0.6,
    quantity: 35,
    stock: 35,
    maxStock: 70,
    minStock: 15,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.4,
  },
  {
    name: 'Beef Steak',
    category: 'Meat',
    description: 'Tender beef steak',
    price: 7.0,
    quantity: 15,
    stock: 15,
    maxStock: 30,
    minStock: 10,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 5.5,
  },
  {
    name: 'Shrimp',
    category: 'Seafood',
    description: 'Large shrimp',
    price: 9.0,
    quantity: 12,
    stock: 12,
    maxStock: 24,
    minStock: 6,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 7.5,
  },
  {
    name: 'Lettuce',
    category: 'Vegetable',
    description: 'Crisp lettuce head',
    price: 1.0,
    quantity: 30,
    stock: 30,
    maxStock: 60,
    minStock: 15,
    expirationDate: '2023-12-31',
    unit: 'piece',
    purchasePrice: 0.8,
  },
  {
    name: 'Peanut Butter',
    category: 'Other',
    description: 'Creamy peanut butter',
    price: 3.0,
    quantity: 20,
    stock: 20,
    maxStock: 40,
    minStock: 10,
    expirationDate: '2023-12-31',
    unit: 'jar',
    purchasePrice: 2.2,
  },
  {
    name: 'Lamb Chops',
    category: 'Meat',
    description: 'Tender lamb chops',
    price: 6.0,
    quantity: 18,
    stock: 18,
    maxStock: 36,
    minStock: 9,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 4.5,
  },
  {
    name: 'Cod',
    category: 'Seafood',
    description: 'Fresh cod fillet',
    price: 7.5,
    quantity: 14,
    stock: 14,
    maxStock: 28,
    minStock: 7,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 6.0,
  },
  {
    name: 'Onion',
    category: 'Vegetable',
    description: 'Sweet onion',
    price: 0.7,
    quantity: 40,
    stock: 40,
    maxStock: 80,
    minStock: 20,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.5,
  },
  {
    name: 'Rice',
    category: 'Other',
    description: 'Basmati rice',
    price: 2.0,
    quantity: 25,
    stock: 25,
    maxStock: 50,
    minStock: 12,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 1.5,
  },
  {
    name: 'Pork Chops',
    category: 'Meat',
    description: 'Bone-in pork chops',
    price: 4.5,
    quantity: 20,
    stock: 20,
    maxStock: 40,
    minStock: 10,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 3.5,
  },
  {
    name: 'Tuna',
    category: 'Seafood',
    description: 'Canned tuna in water',
    price: 1.5,
    quantity: 30,
    stock: 30,
    maxStock: 60,
    minStock: 15,
    expirationDate: '2023-12-31',
    unit: 'can',
    purchasePrice: 1.0,
  },
  {
    name: 'Bell Pepper',
    category: 'Vegetable',
    description: 'Colorful bell pepper',
    price: 1.2,
    quantity: 35,
    stock: 35,
    maxStock: 70,
    minStock: 17,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 0.9,
  },
  {
    name: 'Olive Oil',
    category: 'Other',
    description: 'Extra virgin olive oil',
    price: 5.0,
    quantity: 10,
    stock: 10,
    maxStock: 20,
    minStock: 5,
    expirationDate: '2023-12-31',
    unit: 'bottle',
    purchasePrice: 3.8,
  },
  {
    name: 'Ground Beef',
    category: 'Meat',
    description: 'Ground beef',
    price: 4.0,
    quantity: 25,
    stock: 25,
    maxStock: 50,
    minStock: 12,
    expirationDate: '2023-12-31',
    unit: 'kg',
    purchasePrice: 3.0,
  },
];


  
  itemsToAdd.forEach((item, index) => {
    item.id = index + 1; 
  });
  
  // Function to add items to the database
  const addItemsToDatabase = (items) => {
    const db = require('./database'); 
  
    
  const insertStatement = db.prepare(`
  INSERT INTO products (name, category, description, price, quantity, stock, maxStock, minStock, expirationDate, unit, purchasePrice)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

items.forEach((item) => {
  insertStatement.run(
    item.name,
    item.category,
    item.description,
    item.price,
    item.quantity,
    item.stock,
    item.maxStock,
    item.minStock,
    item.expirationDate,
    item.unit,
    item.purchasePrice
  );
});
    
  };
  const populate = () =>{

      addItemsToDatabase(itemsToAdd);
  }
  module.exports = populate;
  